algorithms:
  - name: autoencoder
    reportFile: "allReports.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "au_model.zip"
        parameters:
          latent_size: 5
          epochs: 2
    test:
      - data_file: "dataset.csv"
        model_input: "au_model.zip"
  - name: cblof
    reportFile: "allReports.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "cblog_model.pkl"
        parameters:
          n_clusters: 5
          alpha: 0.5
    test:
      - data_file: "dataset.csv"
        model_input: "cblog_model.pkl"
  - name: cof
    reportFile: "allReports.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "cof_model.pkl"
        parameters:
          n_neighbors: 30
          method: "fast"
    test:
      - data_file: "dataset.csv"
        model_input: "cof_model.pkl"
  - name: dae
    reportFile: "allReports.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "dae_model.pkl"
        parameters:
          latent_size: 30
          epochs: 5
    test:
      - data_file: "dataset.csv"
        model_input: "dae_model.pkl"
    train-test:
      - data_file_test: "dataset.csv"
        data_file_train: "dataset.csv"
        model: "dae_model.zip"
        parameters:
          latent_size: 10
  - name: hbos
    reportFile: "allReports.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "hbos_model.pkl"
        parameters:
          n_bins: 8
          alpha: 0.2
    test:
      - data_file: "dataset.csv"
        model_input: "hbos_model.pkl"
  - name: knn
    reportFile: "allReports.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "knn_model.pkl"
        parameters:
          n_neighbors: 4
          method: "fast"
    test:
      - data_file: "dataset.csv"
        model_input: "knn_model.pkl"
  - name: lof
    reportFile: "allReports.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "lof_model.pkl"
        parameters:
          n_neighbors: 4
          leaf_size: 20
    test:
      - data_file: "dataset.csv"
        model_input: "lof_model.pkl"
  - name: lstmvae
    reportFile: "allReports.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "lstmvae_model.pkl"
        parameters:
          learning_rate: 0.002
          epochs: 5
    test:
      - data_file: "dataset.csv"
        model_input: "lstmvae_model.pkl"
