algorithms:
  - name: dae
    reportFile: allReports.csv
    train:
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_1.csv
        model_output: dae_average_activity_type_clicks_avg_model_seed_114_fold_1.pkl
        parameters:
          seed: 114
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_2.csv
        model_output: dae_average_activity_type_clicks_avg_model_seed_114_fold_2.pkl
        parameters:
          seed: 114
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_3.csv
        model_output: dae_average_activity_type_clicks_avg_model_seed_114_fold_3.pkl
        parameters:
          seed: 114
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_4.csv
        model_output: dae_average_activity_type_clicks_avg_model_seed_114_fold_4.pkl
        parameters:
          seed: 114
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_5.csv
        model_output: dae_average_activity_type_clicks_avg_model_seed_114_fold_5.pkl
        parameters:
          seed: 114
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_1.csv
        model_output: dae_average_activity_type_clicks_sum_model_seed_114_fold_1.pkl
        parameters:
          seed: 114
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_2.csv
        model_output: dae_average_activity_type_clicks_sum_model_seed_114_fold_2.pkl
        parameters:
          seed: 114
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_3.csv
        model_output: dae_average_activity_type_clicks_sum_model_seed_114_fold_3.pkl
        parameters:
          seed: 114
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_4.csv
        model_output: dae_average_activity_type_clicks_sum_model_seed_114_fold_4.pkl
        parameters:
          seed: 114
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_5.csv
        model_output: dae_average_activity_type_clicks_sum_model_seed_114_fold_5.pkl
        parameters:
          seed: 114
    test:
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_1.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_1.pkl
      - data_file: average_activity_type_clicks_avg/test_fold_1.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_1.pkl
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_2.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_2.pkl
      - data_file: average_activity_type_clicks_avg/test_fold_2.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_2.pkl
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_3.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_3.pkl
      - data_file: average_activity_type_clicks_avg/test_fold_3.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_3.pkl
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_4.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_4.pkl
      - data_file: average_activity_type_clicks_avg/test_fold_4.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_4.pkl
      - data_file: average_activity_type_clicks_avg/train_no_anomaly_fold_5.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_5.pkl
      - data_file: average_activity_type_clicks_avg/test_fold_5.csv
        model_input: dae_average_activity_type_clicks_avg_model_seed_114_fold_5.pkl
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_1.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_1.pkl
      - data_file: average_activity_type_clicks_sum/test_fold_1.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_1.pkl
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_2.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_2.pkl
      - data_file: average_activity_type_clicks_sum/test_fold_2.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_2.pkl
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_3.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_3.pkl
      - data_file: average_activity_type_clicks_sum/test_fold_3.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_3.pkl
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_4.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_4.pkl
      - data_file: average_activity_type_clicks_sum/test_fold_4.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_4.pkl
      - data_file: average_activity_type_clicks_sum/train_no_anomaly_fold_5.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_5.pkl
      - data_file: average_activity_type_clicks_sum/test_fold_5.csv
        model_input: dae_average_activity_type_clicks_sum_model_seed_114_fold_5.pkl
