algorithms:
- name: cblof
  reportFile: allReports.csv
  train:
  - data_file: average_activity_type_clicks_avg/train_fold_1.csv
    model_output: cblof_model_seed_114_fold_1.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_2.csv
    model_output: cblof_model_seed_114_fold_2.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_3.csv
    model_output: cblof_model_seed_114_fold_3.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_4.csv
    model_output: cblof_model_seed_114_fold_4.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_5.csv
    model_output: cblof_model_seed_114_fold_5.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_1.csv
    model_output: cblof_model_seed_114_fold_1.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_2.csv
    model_output: cblof_model_seed_114_fold_2.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_3.csv
    model_output: cblof_model_seed_114_fold_3.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_4.csv
    model_output: cblof_model_seed_114_fold_4.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_5.csv
    model_output: cblof_model_seed_114_fold_5.pkl
    parameters:
      seed: 114
  test:
  - data_file: average_activity_type_clicks_avg/train_fold_1.csv
    model_input: cblof_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_1.csv
    model_input: cblof_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_2.csv
    model_input: cblof_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_2.csv
    model_input: cblof_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_3.csv
    model_input: cblof_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_3.csv
    model_input: cblof_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_4.csv
    model_input: cblof_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_4.csv
    model_input: cblof_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_5.csv
    model_input: cblof_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_5.csv
    model_input: cblof_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_1.csv
    model_input: cblof_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_1.csv
    model_input: cblof_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_2.csv
    model_input: cblof_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_2.csv
    model_input: cblof_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_3.csv
    model_input: cblof_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_3.csv
    model_input: cblof_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_4.csv
    model_input: cblof_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_4.csv
    model_input: cblof_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_5.csv
    model_input: cblof_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_5.csv
    model_input: cblof_model_seed_114_fold_5.pkl
- name: hbos
  reportFile: allReports.csv
  train:
  - data_file: average_activity_type_clicks_avg/train_fold_1.csv
    model_output: hbos_model_seed_114_fold_1.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_2.csv
    model_output: hbos_model_seed_114_fold_2.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_3.csv
    model_output: hbos_model_seed_114_fold_3.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_4.csv
    model_output: hbos_model_seed_114_fold_4.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_5.csv
    model_output: hbos_model_seed_114_fold_5.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_1.csv
    model_output: hbos_model_seed_114_fold_1.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_2.csv
    model_output: hbos_model_seed_114_fold_2.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_3.csv
    model_output: hbos_model_seed_114_fold_3.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_4.csv
    model_output: hbos_model_seed_114_fold_4.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_5.csv
    model_output: hbos_model_seed_114_fold_5.pkl
    parameters:
      seed: 114
  test:
  - data_file: average_activity_type_clicks_avg/train_fold_1.csv
    model_input: hbos_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_1.csv
    model_input: hbos_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_2.csv
    model_input: hbos_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_2.csv
    model_input: hbos_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_3.csv
    model_input: hbos_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_3.csv
    model_input: hbos_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_4.csv
    model_input: hbos_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_4.csv
    model_input: hbos_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_5.csv
    model_input: hbos_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_5.csv
    model_input: hbos_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_1.csv
    model_input: hbos_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_1.csv
    model_input: hbos_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_2.csv
    model_input: hbos_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_2.csv
    model_input: hbos_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_3.csv
    model_input: hbos_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_3.csv
    model_input: hbos_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_4.csv
    model_input: hbos_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_4.csv
    model_input: hbos_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_5.csv
    model_input: hbos_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_5.csv
    model_input: hbos_model_seed_114_fold_5.pkl
- name: knn
  reportFile: allReports.csv
  train:
  - data_file: average_activity_type_clicks_avg/train_fold_1.csv
    model_output: knn_model_seed_114_fold_1.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_2.csv
    model_output: knn_model_seed_114_fold_2.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_3.csv
    model_output: knn_model_seed_114_fold_3.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_4.csv
    model_output: knn_model_seed_114_fold_4.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_5.csv
    model_output: knn_model_seed_114_fold_5.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_1.csv
    model_output: knn_model_seed_114_fold_1.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_2.csv
    model_output: knn_model_seed_114_fold_2.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_3.csv
    model_output: knn_model_seed_114_fold_3.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_4.csv
    model_output: knn_model_seed_114_fold_4.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_5.csv
    model_output: knn_model_seed_114_fold_5.pkl
    parameters:
      seed: 114
  test:
  - data_file: average_activity_type_clicks_avg/train_fold_1.csv
    model_input: knn_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_1.csv
    model_input: knn_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_2.csv
    model_input: knn_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_2.csv
    model_input: knn_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_3.csv
    model_input: knn_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_3.csv
    model_input: knn_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_4.csv
    model_input: knn_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_4.csv
    model_input: knn_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_5.csv
    model_input: knn_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_5.csv
    model_input: knn_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_1.csv
    model_input: knn_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_1.csv
    model_input: knn_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_2.csv
    model_input: knn_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_2.csv
    model_input: knn_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_3.csv
    model_input: knn_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_3.csv
    model_input: knn_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_4.csv
    model_input: knn_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_4.csv
    model_input: knn_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_5.csv
    model_input: knn_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_5.csv
    model_input: knn_model_seed_114_fold_5.pkl
- name: lof
  reportFile: allReports.csv
  train:
  - data_file: average_activity_type_clicks_avg/train_fold_1.csv
    model_output: lof_model_seed_114_fold_1.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_2.csv
    model_output: lof_model_seed_114_fold_2.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_3.csv
    model_output: lof_model_seed_114_fold_3.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_4.csv
    model_output: lof_model_seed_114_fold_4.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_avg/train_fold_5.csv
    model_output: lof_model_seed_114_fold_5.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_1.csv
    model_output: lof_model_seed_114_fold_1.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_2.csv
    model_output: lof_model_seed_114_fold_2.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_3.csv
    model_output: lof_model_seed_114_fold_3.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_4.csv
    model_output: lof_model_seed_114_fold_4.pkl
    parameters:
      seed: 114
  - data_file: average_activity_type_clicks_sum/train_fold_5.csv
    model_output: lof_model_seed_114_fold_5.pkl
    parameters:
      seed: 114
  test:
  - data_file: average_activity_type_clicks_avg/train_fold_1.csv
    model_input: lof_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_1.csv
    model_input: lof_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_2.csv
    model_input: lof_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_2.csv
    model_input: lof_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_3.csv
    model_input: lof_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_3.csv
    model_input: lof_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_4.csv
    model_input: lof_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_4.csv
    model_input: lof_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_avg/train_fold_5.csv
    model_input: lof_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_avg/test_fold_5.csv
    model_input: lof_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_1.csv
    model_input: lof_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_1.csv
    model_input: lof_model_seed_114_fold_1.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_2.csv
    model_input: lof_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_2.csv
    model_input: lof_model_seed_114_fold_2.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_3.csv
    model_input: lof_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_3.csv
    model_input: lof_model_seed_114_fold_3.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_4.csv
    model_input: lof_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_4.csv
    model_input: lof_model_seed_114_fold_4.pkl
  - data_file: average_activity_type_clicks_sum/train_fold_5.csv
    model_input: lof_model_seed_114_fold_5.pkl
  - data_file: average_activity_type_clicks_sum/test_fold_5.csv
    model_input: lof_model_seed_114_fold_5.pkl
