algorithms:
  - name: autoencoder
    reportFile: "allReports.csv"
    train-test:
      - data_file_test: "dataset.csv"
        data_file_train: "dataset.csv"
        model: "au_model.zip"
        parameters:
          latent_size: 5
          epochs: 2
