algorithms:
  - name: lstm_vae
    executions:
      - file_name: "dataset.csv"
        parameters:
          learning_rate: 0.001
          epochs: 10
      - file_name: "dataset.csv"
        parameters:
          learning_rate: 0.002
          epochs: 20
