algorithms:
  - name: dae
    reportFile: "dae.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "dae_model.pkl"
        parameters:
          epochs: 12
          latent_size: 31
    test:
      - data_file: "dataset.csv"
        model_input: "dae_model.pkl"
