algorithms:
  - name: autoencoder
    reportFile: "autoencoder.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "autoencoder_model.pkl"
        parameters:
          epochs: 12
          latent_size: 31
    test:
      - data_file: "dataset.csv"
        model_input: "autoencoder_model.pkl"
