algorithms:
  - name: cblof
    reportFile: allReports.csv
    train:
      - data_file: activity_type_clicks/train_fold_1.csv
        model_output: cblof_model_seed_114_fold_1.pkl
        parameters:
          seed: 114
          n_clusters: 100
    test:
      - data_file: activity_type_clicks/train_fold_1.csv
        model_input: cblof_model_seed_114_fold_1.pkl
      - data_file: activity_type_clicks/test_fold_1.csv
        model_input: cblof_model_seed_114_fold_1.pkl
  - name: hbos
    reportFile: allReports.csv
    train:
      - data_file: activity_type_clicks/train_fold_1.csv
        model_output: hbos_model_seed_114_fold_1.pkl
        parameters:
          seed: 114
    test:
      - data_file: activity_type_clicks/train_fold_1.csv
        model_input: hbos_model_seed_114_fold_1.pkl
      - data_file: activity_type_clicks/test_fold_1.csv
        model_input: hbos_model_seed_114_fold_1.pkl
  - name: knn
    reportFile: allReports.csv
    train:
      - data_file: activity_type_clicks/train_fold_1.csv
        model_output: knn_model_seed_114_fold_1.pkl
        parameters:
          seed: 114
    test:
      - data_file: activity_type_clicks/train_fold_1.csv
        model_input: knn_model_seed_114_fold_1.pkl
      - data_file: activity_type_clicks/test_fold_1.csv
        model_input: knn_model_seed_114_fold_1.pkl
  - name: lof
    reportFile: allReports.csv
    train:
      - data_file: activity_type_clicks/train_fold_1.csv
        model_output: lof_model_seed_114_fold_1.pkl
        parameters:
          seed: 114
    test:
      - data_file: activity_type_clicks/train_fold_1.csv
        model_input: lof_model_seed_114_fold_1.pkl
      - data_file: activity_type_clicks/test_fold_1.csv
        model_input: lof_model_seed_114_fold_1.pkl
