algorithms:
  - name: dae
    reportFile: "allReports.csv"
    train:
      - data_file: "dataset.csv"
        model_output: "dae_model.pkl"
        parameters:
          latent_size: 30
          epochs: 5
    test:
      - data_file: "dataset.csv"
        model_input: "dae_model.pkl"
    train-test:
      - data_file_test: "dataset.csv"
        data_file_train: "dataset.csv"
        model: "dae_model.zip"
        parameters:
          latent_size: 10
